version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_HOST=dpg-ct5qi63qf0us7388dh7g-a.oregon-postgres.render.com
      - DATABASE_PORT=5432
      - DATABASE_NAME=altclan_90zq
      - DATABASE_USER=altclan_90zq_user
      - DATABASE_PASSWORD=yHvbGCl0APFJzTfatTw3wBtmGPNOaYeV
