version: '3.8'
services:
  web:
    build: .
    command: daphne altclan.asgi:application --bind 0.0.0.0 --port ${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
      - DATABASE_URL=postgresql://altclan_u80j_user:4SkI6hC6Zj9pptNym9IZmCOpdCie3dxK@dpg-d0qhga3ipnbc73ecq650-a.oregon-postgres.render.com/altclan_u80j
      - REDIS_URL=redis://red-d0oua23e5dus73d9hhug:6379
      - DJANGO_SETTINGS_MODULE=altclan.settings
      - SECRET_KEY=django-insecure-#ioqb6nvy+hwu5(%r@(dv!6zztc7vb*+altclbrandsapivhihr5*oe
      - ALLOWED_HOSTS=altclan-brands-api-1-1.onrender.com,localhost,127.0.0.1