version: '3.8'
services:
  web:
    build: .
    command: gunicorn altclan.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://altclan_svfm_user:QTu317BmDkhFKEnK8xHeoK1BajSaBbID@dpg-cvvcnl2dbo4c73aqtu10-a.oregon-postgres.render.com/altclan_svfm