version: '3.8'
services:
  web:
    build: .
    command: daphne altclan.asgi:application --bind 0.0.0.0:8000  # Updated
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://altclan_jr88_user:Q069W2ENBamJI8BGwYpH35IVD1eDxKoP@dpg-d0m4pgruibrs73851mh0-a.oregon-postgres.render.com/altclan_jr88