version: '3.8'
services:
  web:
    build: .
    command: gunicorn altclan.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=