version: '3.8'
services:
  web:
    build: .
    command: gunicorn altclan.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://altclan_ij7z_user:JRi5TkXQF7gQcJePaO2Zv577QXUrPp35@dpg-cts0d6t2ng1s73bta120-a.oregon-postgres.render.com/altclan_ij7z
