version: '3.8'
services:
  web:
    build: .
    command: daphne altclan.asgi:application --bind 0.0.0.0:$PORT
    environment:
      - DATABASE_URL=postgresql://altclan_h6ib_user:0zhEXWmY9YYFbR4pVzNBdmQmMHC1mg0f@dpg-d0oo7u0dl3ps73a5m080-a.oregon-postgres.render.com/altclan_h6ib
      - REDIS_URL=redis://red-d0oua23e5dus73d9hhug:6379
      # PORT will be automatically provided by Render