version: '3.8'
services:
  web:
    build: .
    command: gunicorn altclan.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://altclan_vnux_user:Col11mdJHUGwoAdP37lCKjbazJd7SBoK@dpg-cul1orl2ng1s7382qfsg-a.oregon-postgres.render.com/altclan_vnux