services:
  - name: altclan-brands-api-1-1
    type: web
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /health/
    region: oregon
    envVarGroups:
      - altclan-production-2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: altclan.settings
      - key: PORT
        value: 8000
    autoDeploy: true
    branch: main