services:
  - name: altclan-brands-api-1-1
    type: web
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: sh -c 'daphne altclan.asgi:application --bind 0.0.0.0 --port $PORT'
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: altclan.settings
      - key: SECRET_KEY
        value: django-insecure-#ioqb6nvy+hwu5(%r@(dv!6zztc7vb*+altclbrandsapivhihr5*oe
      - key: ALLOWED_HOSTS
        value: altclan-brands-api-1-1.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: DATABASE_URL
        value: postgresql://altclan_u80j_user:4SkI6hC6Zj9pptNym9IZmCOpdCie3dxK@dpg-d0qhga3ipnbc73ecq650-a.oregon-postgres.render.com/altclan_u80j
      - key: REDIS_URL
        value: redis://red-d0oua23e5dus73d9hhug:6379