# Generated by Django 4.2 on 2026-08-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='stock_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
