# Generated by Django 3.2.5 on 2024-05-03 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 14, 15, 39, 253241, tzinfo=utc)),
        ),
    ]
