# Generated by Django 4.2 on 2025-02-15 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 8, 14, 29, 670520, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 8, 14, 29, 668523, tzinfo=datetime.timezone.utc)),
        ),
    ]
