# Generated by Django 4.2 on 2026-01-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='image_5',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='total_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
