# Generated by Django 4.2 on 2025-05-24 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 14, 55, 42, 89293, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 14, 55, 42, 92294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 14, 55, 42, 88292, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='merchandisegallery',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 14, 55, 42, 93708, tzinfo=datetime.timezone.utc)),
        ),
    ]
