# Generated by Django 4.2 on 2026-01-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_remove_merchandise_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='commission_fee',
            field=models.FloatField(blank=True, default=0.15, null=True),
        ),
    ]
