# Generated by Django 4.2 on 2025-05-27 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_blog_date_created_alter_gallery_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 1, 31, 25, 414055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 1, 31, 25, 416055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 1, 31, 25, 414055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='merchandisegallery',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 1, 31, 25, 416055, tzinfo=datetime.timezone.utc)),
        ),
    ]
