# Generated by Django 4.2 on 2025-02-15 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_gallery_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 16, 8, 59, 189671, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 16, 8, 59, 186689, tzinfo=datetime.timezone.utc)),
        ),
    ]
