# Generated by Django 4.2 on 2025-02-15 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_gallery_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 17, 28, 38, 62353, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 17, 28, 38, 60401, tzinfo=datetime.timezone.utc)),
        ),
    ]
