# Generated by Django 3.2.5 on 2024-12-01 00:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 0, 26, 12, 549529, tzinfo=utc)),
        ),
    ]
