# Generated by Django 3.2.5 on 2024-07-17 21:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_auto_20240717_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 21, 39, 9, 76059, tzinfo=utc)),
        ),
    ]
