# Generated by Django 3.2.5 on 2024-06-13 20:47

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='available_colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='available_sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 20, 47, 2, 561597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='display_image',
            field=models.URLField(),
        ),
    ]
