# Generated by Django 3.2.5 on 2024-07-26 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='color_type',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 20, 58, 25, 795816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='labels',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
