# Generated by Django 4.2 on 2026-08-31 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('pathname', models.CharField(blank=True, max_length=2048, null=True)),
                ('referrer', models.URLField(blank=True, max_length=2048, null=True)),
                ('cookies', models.JSONField(blank=True, default=dict)),
                ('local_storage', models.JSONField(blank=True, default=dict)),
                ('session_storage', models.JSONField(blank=True, default=dict)),
                ('operating_system', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('browser', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('online', models.BooleanField(default=True)),
                ('screen', models.JSONField(blank=True, default=dict)),
                ('connection', models.JSONField(blank=True, default=dict)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], max_length=32)),
                ('item_id', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
