# Generated by Django 4.2 on 2025-06-28 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 7, 2, 0, 32075, tzinfo=datetime.timezone.utc)),
        ),
    ]
