# Generated by Django 4.2 on 2026-01-13 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 13, 19, 48, 58, 225131, tzinfo=datetime.timezone.utc)),
        ),
    ]
