# Generated by Django 4.2 on 2026-08-21 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_customers_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 21, 16, 52, 31, 437700, tzinfo=datetime.timezone.utc)),
        ),
    ]
