# Generated by Django 4.2 on 2025-05-27 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_customers_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 1, 31, 25, 418052, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
