# Generated by Django 4.2 on 2025-08-28 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_customers_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 10, 46, 56, 215206, tzinfo=datetime.timezone.utc)),
        ),
    ]
