# Generated by Django 4.2 on 2025-12-13 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_customers_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 13, 19, 8, 48, 522092, tzinfo=datetime.timezone.utc)),
        ),
    ]
