# Generated by Django 4.2 on 2026-01-16 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_customers_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 15, 34, 8, 964581, tzinfo=datetime.timezone.utc)),
        ),
    ]
