# Generated by Django 4.2 on 2025-07-14 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_customers_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 20, 55, 42, 769905, tzinfo=datetime.timezone.utc)),
        ),
    ]
