# Generated by Django 4.2 on 2026-08-31 13:09

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('brand_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('brand_logo', models.URLField(blank=True, default='', null=True)),
                ('brand_bio', models.TextField(blank=True, default='', null=True)),
                ('brand_type', models.CharField(blank=True, choices=[('Clothing & Apparel', 'Clothing & Apparel'), ('Streetwear', 'Streetwear'), ('Kids Clothing', 'Kids Clothing'), ('Accessories', 'Accessories'), ('Jewelleries', 'Jewelleries'), ('Fragrance', 'Fragrance'), ('Resale', 'Resale'), ('Interior Design', 'Interior Design'), ('Thrift Store', 'Thrift Store'), ('Arts & Crafts', 'Arts & Crafts'), ('Footwears', 'Footwears'), ('Enigmas', 'Enigmas'), ('Watches', 'Watches'), ('Skates', 'Skates'), ('Caps', 'Caps'), ('Masks', 'Masks'), ('Gothic', 'Gothic'), ('Sportswear', 'Sportswear'), ('Native Attires', 'Native Attires'), ('Suits', 'Suits'), ('Wedding Gowns', 'Wedding Gowns'), ('Ties', 'Ties'), ('Cuff Links', 'Cuff Links'), ('Socks', 'Socks'), ('Slides', 'Slides'), ('Beads', 'Beads'), ('Tracksuits', 'Tracksuits'), ('Denim', 'Denim'), ('Gloves', 'Gloves'), ('Masks', 'Masks'), ('Dresses', 'Dresses'), ('Nose Rings', 'Nose Rings'), ('Ear Rings', 'Ear Rings'), ('Bags', 'Bags'), ('Aesthetics', 'Aesthetics'), ('Boutique', 'Boutique'), ('Luxury', 'Luxury'), ('Lingerie', 'Lingerie'), ('Swimwears', 'Swimwears'), ('Chrochet', 'Chrochet')], default='', max_length=250, null=True)),
                ('brand_category', models.CharField(blank=True, choices=[('Original', 'Original'), ('Reseller', 'Reseller')], default='', max_length=250, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('followers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), default=list, size=None)),
                ('wish_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), default=list, size=None)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('billing_address', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('zip', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'pending'), ('suspended', 'suspended'), ('locked', 'locked'), ('deleted', 'deleted')], default='active', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2026, 8, 31, 13, 9, 11, 816732, tzinfo=datetime.timezone.utc))),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
