# Generated by Django 4.2 on 2026-01-16 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 17, 30, 45, 608176, tzinfo=datetime.timezone.utc)),
        ),
    ]
