# Generated by Django 4.2 on 2025-12-04 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 4, 10, 30, 6, 884215, tzinfo=datetime.timezone.utc)),
        ),
    ]
