# Generated by Django 4.2 on 2026-08-27 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 27, 14, 48, 16, 337587, tzinfo=datetime.timezone.utc)),
        ),
    ]
