# Generated by Django 4.2 on 2026-01-13 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 13, 20, 18, 17, 555200, tzinfo=datetime.timezone.utc)),
        ),
    ]
