# Generated by Django 4.2 on 2026-01-16 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brand_category',
            field=models.CharField(blank=True, choices=[('Original', 'Original'), ('Reseller', 'Reseller')], default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 15, 34, 8, 962807, tzinfo=datetime.timezone.utc)),
        ),
    ]
