# Generated by Django 4.2 on 2026-10-07 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='brand_type',
            field=models.CharField(blank=True, choices=[('Clothing & Apparel', 'Clothing & Apparel'), ('Streetwear', 'Streetwear'), ('Kids Clothing', 'Kids Clothing'), ('Accessories', 'Accessories'), ('Jewelleries', 'Jewelleries'), ('Fragrance', 'Fragrance'), ('Resale', 'Resale'), ('Interior Design', 'Interior Design'), ('Thrift Store', 'Thrift Store'), ('Arts & Crafts', 'Arts & Crafts'), ('Footwears', 'Footwears'), ('Enigmas', 'Enigmas'), ('Watches', 'Watches'), ('Skates', 'Skates'), ('Caps', 'Caps'), ('Masks', 'Masks'), ('Gothic', 'Gothic'), ('Sportswear', 'Sportswear'), ('Native Attires', 'Native Attires'), ('Suits', 'Suits'), ('Wedding Gowns', 'Wedding Gowns'), ('Ties', 'Ties'), ('Cuff Links', 'Cuff Links'), ('Socks', 'Socks'), ('Slides', 'Slides'), ('Beads', 'Beads'), ('Tracksuits', 'Tracksuits'), ('Denim', 'Denim'), ('Gloves', 'Gloves'), ('Masks', 'Masks'), ('Dresses', 'Dresses'), ('Nose Rings', 'Nose Rings'), ('Ear Rings', 'Ear Rings'), ('Bags', 'Bags'), ('Aesthetics', 'Aesthetics'), ('Boutique', 'Boutique'), ('Luxury', 'Luxury'), ('Lingerie', 'Lingerie'), ('Swimwears', 'Swimwears'), ('Crochet', 'Crochet'), ('Handmade', 'Handmade'), ('Vintage Shirts', 'Vintage Shirts')], default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 10, 7, 9, 14, 46, 935548, tzinfo=datetime.timezone.utc)),
        ),
    ]
