# Generated by Django 4.2 on 2025-12-13 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='billing_address',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='brand_bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='brand_logo',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='brand_type',
            field=models.CharField(blank=True, choices=[('Clothing & Apparel', 'Clothing & Apparel'), ('Streetwear', 'Streetwear'), ('Kids Clothing', 'Kids Clothing'), ('Accessories', 'Accessories'), ('Jewelleries', 'Jewelleries'), ('Resale wears', 'Resale wears'), ('Thrift wears', 'Thrift wears'), ('Arts & Aesthetics', 'Arts & Aesthetics'), ('Footwears', 'Footwears'), ('Enigmas', 'Enigmas'), ('Watches', 'Watches'), ('Skates', 'Skates'), ('Caps', 'Caps'), ('Masks', 'Masks'), ('Gothic', 'Gothic')], default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zip',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 13, 19, 8, 48, 513342, tzinfo=datetime.timezone.utc)),
        ),
    ]
