# Generated by Django 3.2.5 on 2024-07-13 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240624_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 7, 58, 42, 447520, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='brand_logo',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 7, 58, 42, 447520, tzinfo=utc)),
        ),
    ]
