# Generated by Django 4.2 on 2025-02-15 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_brandprofile_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 17, 28, 38, 59347, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 17, 28, 38, 58414, tzinfo=datetime.timezone.utc)),
        ),
    ]
