# Generated by Django 4.2 on 2025-06-28 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_brandprofile_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 20, 35, 42, 846428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 20, 35, 42, 846428, tzinfo=datetime.timezone.utc)),
        ),
    ]
