# Generated by Django 4.2 on 2026-01-16 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_brand_category_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 17, 13, 17, 196424, tzinfo=datetime.timezone.utc)),
        ),
    ]
