# Generated by Django 4.2 on 2025-07-14 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_brandprofile_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 20, 55, 42, 761751, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 20, 55, 42, 761751, tzinfo=datetime.timezone.utc)),
        ),
    ]
