# Generated by Django 4.2 on 2026-01-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='email',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
