# Generated by Django 4.2 on 2025-02-18 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 21, 29, 15, 781118, tzinfo=datetime.timezone.utc)),
        ),
    ]
