# Generated by Django 4.2 on 2025-02-15 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 8, 14, 29, 674521, tzinfo=datetime.timezone.utc)),
        ),
    ]
