# Generated by Django 4.2 on 2025-05-24 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 14, 55, 42, 106444, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 14, 55, 42, 106444, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 14, 55, 42, 108446, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 14, 55, 42, 104445, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 14, 55, 42, 105444, tzinfo=datetime.timezone.utc)),
        ),
    ]
