# Generated by Django 4.2 on 2025-02-15 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 16, 8, 59, 194669, tzinfo=datetime.timezone.utc)),
        ),
    ]
