# Generated by Django 4.2 on 2026-01-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_paymentmethod_email'),
    ]

    
    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(
                max_length=250, 
                null=True, 
                blank=True, 
                choices=[
                    ('Transfer', 'Transfer'),
                    ('Card', 'Card'),
                    ('USSD', 'USSD'),
                    ('Paystack', 'Paystack'),
                    ('Opay', 'Opay')
                ], 
                default='Paystack'
            ),
        ),
    ]
