# Generated by Django 4.2 on 2025-05-27 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_coupon_end_date_alter_coupon_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='email',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='email',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='email',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='email',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 1, 31, 25, 422050, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 1, 31, 25, 422050, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 1, 31, 25, 422050, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 1, 31, 25, 421051, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 1, 31, 25, 421051, tzinfo=datetime.timezone.utc)),
        ),
    ]
