# Generated by Django 4.2 on 2025-02-15 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_item_order_items_alter_order_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 17, 35, 22, 325376, tzinfo=datetime.timezone.utc)),
        ),
    ]
