# Generated by Django 4.2 on 2025-05-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='merchandise_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='merchandise_slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
