# Generated by Django 3.2.5 on 2024-07-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='brand_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
