# Generated by Django 4.2 on 2026-01-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='individual_rating',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
