# Generated by Django 4.2 on 2026-01-28 05:08

from django.db import migrations, models
import django.contrib.postgres.fields

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        # Add max_rating if missing
        migrations.AddField(
            model_name='ratings',
            name='max_rating',
            field=models.IntegerField(null=True, blank=True),
        ),
        # Add cummulative_rating if missing
        migrations.AddField(
            model_name='ratings',
            name='cummulative_rating',
            field=models.FloatField(null=True, blank=True),
        ),
        # Add rating array if missing
        migrations.AddField(
            model_name='ratings',
            name='rating',
            field=django.contrib.postgres.fields.ArrayField(
                models.IntegerField(), 
                default=list, 
                size=None
            ),
        ),
        # Add overall_score if missing
        migrations.AddField(
            model_name='ratings',
            name='overall_score',
            field=models.CharField(max_length=250, null=True, blank=True),
        ),
    ]
