# Generated by Django 3.2.5 on 2024-07-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
