# Generated by Django 4.2 on 2026-01-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_add_individual_rating_to_ratings'),
    ]

    operations = [
    ]
