# Generated by Django 4.2 on 2026-01-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_add_missing_fields_to_ratings'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE reviews_ratings 
            ADD COLUMN IF NOT EXISTS individual_rating INTEGER;
            
            ALTER TABLE reviews_ratings 
            ADD COLUMN IF NOT EXISTS max_rating INTEGER;
            
            ALTER TABLE reviews_ratings 
            ADD COLUMN IF NOT EXISTS cummulative_rating DOUBLE PRECISION;
            
            ALTER TABLE reviews_ratings 
            ADD COLUMN IF NOT EXISTS rating INTEGER[] DEFAULT '{}';
            
            ALTER TABLE reviews_ratings 
            ADD COLUMN IF NOT EXISTS overall_score VARCHAR(250);
            """,
            reverse_sql="""
            ALTER TABLE reviews_ratings DROP COLUMN IF EXISTS individual_rating;
            ALTER TABLE reviews_ratings DROP COLUMN IF EXISTS max_rating;
            ALTER TABLE reviews_ratings DROP COLUMN IF EXISTS cummulative_rating;
            ALTER TABLE reviews_ratings DROP COLUMN IF EXISTS rating;
            ALTER TABLE reviews_ratings DROP COLUMN IF EXISTS overall_score;
            """
        ),
    ]