# Generated by Django 3.2.5 on 2024-07-19 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240717_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='slug',
        ),
    ]
