# Generated by Django 4.2 on 2026-08-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_convert_reviews_rating_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='cummulative_rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='max_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='cummulative_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
